/* ==========================================================================
   DEEC Studio — país + ciudad dataset (checkout.html)
   Self-contained, no external API: full country list (ISO-ish, ES/EN
   labels) plus a curated list of major cities per country. Cities are not
   exhaustive — small towns won't be in here — so the checkout's city
   select always offers an "Otra ciudad / Other city" option that reveals a
   free-text field (see initCheckoutGeo() in main.js).
   ========================================================================== */
(function () {
  "use strict";

  window.__GEO__ = {
    countries: [
      { code: "MX", es: "México", en: "Mexico" },
      { code: "US", es: "Estados Unidos", en: "United States" },
      { code: "CA", es: "Canadá", en: "Canada" },
      { code: "GT", es: "Guatemala", en: "Guatemala" },
      { code: "BZ", es: "Belice", en: "Belize" },
      { code: "SV", es: "El Salvador", en: "El Salvador" },
      { code: "HN", es: "Honduras", en: "Honduras" },
      { code: "NI", es: "Nicaragua", en: "Nicaragua" },
      { code: "CR", es: "Costa Rica", en: "Costa Rica" },
      { code: "PA", es: "Panamá", en: "Panama" },
      { code: "CU", es: "Cuba", en: "Cuba" },
      { code: "DO", es: "República Dominicana", en: "Dominican Republic" },
      { code: "PR", es: "Puerto Rico", en: "Puerto Rico" },
      { code: "JM", es: "Jamaica", en: "Jamaica" },
      { code: "HT", es: "Haití", en: "Haiti" },
      { code: "TT", es: "Trinidad y Tobago", en: "Trinidad and Tobago" },
      { code: "BS", es: "Bahamas", en: "Bahamas" },
      { code: "BB", es: "Barbados", en: "Barbados" },
      { code: "CO", es: "Colombia", en: "Colombia" },
      { code: "VE", es: "Venezuela", en: "Venezuela" },
      { code: "EC", es: "Ecuador", en: "Ecuador" },
      { code: "PE", es: "Perú", en: "Peru" },
      { code: "BO", es: "Bolivia", en: "Bolivia" },
      { code: "CL", es: "Chile", en: "Chile" },
      { code: "AR", es: "Argentina", en: "Argentina" },
      { code: "UY", es: "Uruguay", en: "Uruguay" },
      { code: "PY", es: "Paraguay", en: "Paraguay" },
      { code: "BR", es: "Brasil", en: "Brazil" },
      { code: "GY", es: "Guyana", en: "Guyana" },
      { code: "SR", es: "Surinam", en: "Suriname" },
      { code: "ES", es: "España", en: "Spain" },
      { code: "PT", es: "Portugal", en: "Portugal" },
      { code: "FR", es: "Francia", en: "France" },
      { code: "DE", es: "Alemania", en: "Germany" },
      { code: "IT", es: "Italia", en: "Italy" },
      { code: "GB", es: "Reino Unido", en: "United Kingdom" },
      { code: "IE", es: "Irlanda", en: "Ireland" },
      { code: "NL", es: "Países Bajos", en: "Netherlands" },
      { code: "BE", es: "Bélgica", en: "Belgium" },
      { code: "CH", es: "Suiza", en: "Switzerland" },
      { code: "AT", es: "Austria", en: "Austria" },
      { code: "SE", es: "Suecia", en: "Sweden" },
      { code: "NO", es: "Noruega", en: "Norway" },
      { code: "DK", es: "Dinamarca", en: "Denmark" },
      { code: "FI", es: "Finlandia", en: "Finland" },
      { code: "IS", es: "Islandia", en: "Iceland" },
      { code: "PL", es: "Polonia", en: "Poland" },
      { code: "CZ", es: "República Checa", en: "Czech Republic" },
      { code: "SK", es: "Eslovaquia", en: "Slovakia" },
      { code: "HU", es: "Hungría", en: "Hungary" },
      { code: "RO", es: "Rumania", en: "Romania" },
      { code: "BG", es: "Bulgaria", en: "Bulgaria" },
      { code: "GR", es: "Grecia", en: "Greece" },
      { code: "UA", es: "Ucrania", en: "Ukraine" },
      { code: "RU", es: "Rusia", en: "Russia" },
      { code: "RS", es: "Serbia", en: "Serbia" },
      { code: "HR", es: "Croacia", en: "Croatia" },
      { code: "SI", es: "Eslovenia", en: "Slovenia" },
      { code: "BA", es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" },
      { code: "ME", es: "Montenegro", en: "Montenegro" },
      { code: "MK", es: "Macedonia del Norte", en: "North Macedonia" },
      { code: "AL", es: "Albania", en: "Albania" },
      { code: "LT", es: "Lituania", en: "Lithuania" },
      { code: "LV", es: "Letonia", en: "Latvia" },
      { code: "EE", es: "Estonia", en: "Estonia" },
      { code: "MD", es: "Moldavia", en: "Moldova" },
      { code: "BY", es: "Bielorrusia", en: "Belarus" },
      { code: "LU", es: "Luxemburgo", en: "Luxembourg" },
      { code: "MT", es: "Malta", en: "Malta" },
      { code: "CY", es: "Chipre", en: "Cyprus" },
      { code: "AD", es: "Andorra", en: "Andorra" },
      { code: "MC", es: "Mónaco", en: "Monaco" },
      { code: "LI", es: "Liechtenstein", en: "Liechtenstein" },
      { code: "SM", es: "San Marino", en: "San Marino" },
      { code: "VA", es: "Ciudad del Vaticano", en: "Vatican City" },
      { code: "TR", es: "Turquía", en: "Turkey" },
      { code: "CN", es: "China", en: "China" },
      { code: "JP", es: "Japón", en: "Japan" },
      { code: "KR", es: "Corea del Sur", en: "South Korea" },
      { code: "KP", es: "Corea del Norte", en: "North Korea" },
      { code: "TW", es: "Taiwán", en: "Taiwan" },
      { code: "HK", es: "Hong Kong", en: "Hong Kong" },
      { code: "IN", es: "India", en: "India" },
      { code: "PK", es: "Pakistán", en: "Pakistan" },
      { code: "BD", es: "Bangladés", en: "Bangladesh" },
      { code: "NP", es: "Nepal", en: "Nepal" },
      { code: "LK", es: "Sri Lanka", en: "Sri Lanka" },
      { code: "ID", es: "Indonesia", en: "Indonesia" },
      { code: "PH", es: "Filipinas", en: "Philippines" },
      { code: "VN", es: "Vietnam", en: "Vietnam" },
      { code: "TH", es: "Tailandia", en: "Thailand" },
      { code: "MY", es: "Malasia", en: "Malaysia" },
      { code: "SG", es: "Singapur", en: "Singapore" },
      { code: "MM", es: "Myanmar", en: "Myanmar" },
      { code: "KH", es: "Camboya", en: "Cambodia" },
      { code: "LA", es: "Laos", en: "Laos" },
      { code: "MN", es: "Mongolia", en: "Mongolia" },
      { code: "KZ", es: "Kazajistán", en: "Kazakhstan" },
      { code: "UZ", es: "Uzbekistán", en: "Uzbekistan" },
      { code: "GE", es: "Georgia", en: "Georgia" },
      { code: "AM", es: "Armenia", en: "Armenia" },
      { code: "AZ", es: "Azerbaiyán", en: "Azerbaijan" },
      { code: "AF", es: "Afganistán", en: "Afghanistan" },
      { code: "IR", es: "Irán", en: "Iran" },
      { code: "IQ", es: "Irak", en: "Iraq" },
      { code: "SA", es: "Arabia Saudita", en: "Saudi Arabia" },
      { code: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
      { code: "QA", es: "Catar", en: "Qatar" },
      { code: "KW", es: "Kuwait", en: "Kuwait" },
      { code: "BH", es: "Baréin", en: "Bahrain" },
      { code: "OM", es: "Omán", en: "Oman" },
      { code: "JO", es: "Jordania", en: "Jordan" },
      { code: "LB", es: "Líbano", en: "Lebanon" },
      { code: "SY", es: "Siria", en: "Syria" },
      { code: "IL", es: "Israel", en: "Israel" },
      { code: "PS", es: "Palestina", en: "Palestine" },
      { code: "YE", es: "Yemen", en: "Yemen" },
      { code: "EG", es: "Egipto", en: "Egypt" },
      { code: "ZA", es: "Sudáfrica", en: "South Africa" },
      { code: "NG", es: "Nigeria", en: "Nigeria" },
      { code: "KE", es: "Kenia", en: "Kenya" },
      { code: "ET", es: "Etiopía", en: "Ethiopia" },
      { code: "GH", es: "Ghana", en: "Ghana" },
      { code: "MA", es: "Marruecos", en: "Morocco" },
      { code: "DZ", es: "Argelia", en: "Algeria" },
      { code: "TN", es: "Túnez", en: "Tunisia" },
      { code: "LY", es: "Libia", en: "Libya" },
      { code: "SD", es: "Sudán", en: "Sudan" },
      { code: "UG", es: "Uganda", en: "Uganda" },
      { code: "TZ", es: "Tanzania", en: "Tanzania" },
      { code: "CM", es: "Camerún", en: "Cameroon" },
      { code: "CI", es: "Costa de Marfil", en: "Ivory Coast" },
      { code: "SN", es: "Senegal", en: "Senegal" },
      { code: "ML", es: "Mali", en: "Mali" },
      { code: "NE", es: "Níger", en: "Niger" },
      { code: "BF", es: "Burkina Faso", en: "Burkina Faso" },
      { code: "RW", es: "Ruanda", en: "Rwanda" },
      { code: "ZM", es: "Zambia", en: "Zambia" },
      { code: "ZW", es: "Zimbabue", en: "Zimbabwe" },
      { code: "MZ", es: "Mozambique", en: "Mozambique" },
      { code: "AO", es: "Angola", en: "Angola" },
      { code: "CD", es: "Rep. Democrática del Congo", en: "Democratic Republic of the Congo" },
      { code: "CG", es: "Congo", en: "Congo" },
      { code: "GA", es: "Gabón", en: "Gabon" },
      { code: "NA", es: "Namibia", en: "Namibia" },
      { code: "BW", es: "Botsuana", en: "Botswana" },
      { code: "MW", es: "Malaui", en: "Malawi" },
      { code: "SO", es: "Somalia", en: "Somalia" },
      { code: "LR", es: "Liberia", en: "Liberia" },
      { code: "SL", es: "Sierra Leona", en: "Sierra Leone" },
      { code: "GM", es: "Gambia", en: "Gambia" },
      { code: "GN", es: "Guinea", en: "Guinea" },
      { code: "TG", es: "Togo", en: "Togo" },
      { code: "BJ", es: "Benín", en: "Benin" },
      { code: "MG", es: "Madagascar", en: "Madagascar" },
      { code: "MU", es: "Mauricio", en: "Mauritius" },
      { code: "AU", es: "Australia", en: "Australia" },
      { code: "NZ", es: "Nueva Zelanda", en: "New Zealand" },
      { code: "FJ", es: "Fiyi", en: "Fiji" },
      { code: "PG", es: "Papúa Nueva Guinea", en: "Papua New Guinea" }
    ],

    // code -> international dial code, for the checkout phone field's
    // country/lada picker (see initCheckoutPhone() in main.js). Flags
    // are never stored here — they're derived at render time from the
    // ISO code itself (regional-indicator emoji trick), so adding a
    // country above only ever needs its dial code added here too.
    dialCodes: {
      MX: "+52", US: "+1", CA: "+1", GT: "+502", BZ: "+501", SV: "+503", HN: "+504", NI: "+505",
      CR: "+506", PA: "+507", CU: "+53", DO: "+1", PR: "+1", JM: "+1", HT: "+509", TT: "+1",
      BS: "+1", BB: "+1", CO: "+57", VE: "+58", EC: "+593", PE: "+51", BO: "+591", CL: "+56",
      AR: "+54", UY: "+598", PY: "+595", BR: "+55", GY: "+592", SR: "+597", ES: "+34", PT: "+351",
      FR: "+33", DE: "+49", IT: "+39", GB: "+44", IE: "+353", NL: "+31", BE: "+32", CH: "+41",
      AT: "+43", SE: "+46", NO: "+47", DK: "+45", FI: "+358", IS: "+354", PL: "+48", CZ: "+420",
      SK: "+421", HU: "+36", RO: "+40", BG: "+359", GR: "+30", UA: "+380", RU: "+7", RS: "+381",
      HR: "+385", SI: "+386", BA: "+387", ME: "+382", MK: "+389", AL: "+355", LT: "+370", LV: "+371",
      EE: "+372", MD: "+373", BY: "+375", LU: "+352", MT: "+356", CY: "+357", AD: "+376", MC: "+377",
      LI: "+423", SM: "+378", VA: "+379", TR: "+90", CN: "+86", JP: "+81", KR: "+82", KP: "+850",
      TW: "+886", HK: "+852", IN: "+91", PK: "+92", BD: "+880", NP: "+977", LK: "+94", ID: "+62",
      PH: "+63", VN: "+84", TH: "+66", MY: "+60", SG: "+65", MM: "+95", KH: "+855", LA: "+856",
      MN: "+976", KZ: "+7", UZ: "+998", GE: "+995", AM: "+374", AZ: "+994", AF: "+93", IR: "+98",
      IQ: "+964", SA: "+966", AE: "+971", QA: "+974", KW: "+965", BH: "+973", OM: "+968", JO: "+962",
      LB: "+961", SY: "+963", IL: "+972", PS: "+970", YE: "+967", EG: "+20", ZA: "+27", NG: "+234",
      KE: "+254", ET: "+251", GH: "+233", MA: "+212", DZ: "+213", TN: "+216", LY: "+218", SD: "+249",
      UG: "+256", TZ: "+255", CM: "+237", CI: "+225", SN: "+221", ML: "+223", NE: "+227", BF: "+226",
      RW: "+250", ZM: "+260", ZW: "+263", MZ: "+258", AO: "+244", CD: "+243", CG: "+242", GA: "+241",
      NA: "+264", BW: "+267", MW: "+265", SO: "+252", LR: "+231", SL: "+232", GM: "+220", GN: "+224",
      TG: "+228", BJ: "+229", MG: "+261", MU: "+230", AU: "+61", NZ: "+64", FJ: "+679", PG: "+675"
    },

    // code -> major cities (capital first). Not exhaustive on purpose —
    // the UI always offers "Otra ciudad / Other city" as a fallback.
    cities: {
      MX: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Querétaro", "Mérida", "Cancún", "Toluca", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Culiacán", "Chihuahua", "Saltillo", "Morelia", "Veracruz", "Villahermosa", "Oaxaca", "Tuxtla Gutiérrez", "Cuernavaca", "Pachuca", "Tepic", "Durango", "Mazatlán", "Playa del Carmen", "Los Cabos", "Acapulco", "Torreón", "Reynosa", "Matamoros", "Nuevo Laredo", "Ciudad Juárez", "Ensenada", "Mexicali", "La Paz", "Colima", "Zacatecas", "Campeche"],
      US: ["Washington D.C.", "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "Austin", "Miami", "Orlando", "Atlanta", "Charlotte", "Seattle", "Denver", "Boston", "Las Vegas", "Portland", "Nashville", "Memphis", "Detroit", "Minneapolis", "San Francisco", "San Jose", "Sacramento", "Fort Worth", "El Paso", "Jacksonville", "Columbus", "Indianapolis", "Baltimore", "Tampa", "St. Louis", "Pittsburgh", "Cincinnati", "Kansas City", "New Orleans", "Salt Lake City", "Raleigh", "Richmond", "Milwaukee", "Oklahoma City", "Tucson", "Albuquerque", "Fresno", "Long Beach", "Mesa", "Virginia Beach", "Omaha", "Colorado Springs", "Honolulu", "Anchorage"],
      CA: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Quebec", "Winnipeg", "Hamilton"],
      GT: ["Ciudad de Guatemala", "Quetzaltenango", "Antigua Guatemala", "Escuintla"],
      BZ: ["Belmopán", "Belize City", "San Pedro"],
      SV: ["San Salvador", "Santa Ana", "San Miguel"],
      HN: ["Tegucigalpa", "San Pedro Sula", "La Ceiba"],
      NI: ["Managua", "León", "Granada"],
      CR: ["San José", "Alajuela", "Liberia", "Heredia"],
      PA: ["Ciudad de Panamá", "Colón", "David"],
      CU: ["La Habana", "Santiago de Cuba", "Varadero"],
      DO: ["Santo Domingo", "Santiago de los Caballeros", "Punta Cana", "La Romana"],
      PR: ["San Juan", "Ponce", "Bayamón", "Carolina"],
      JM: ["Kingston", "Montego Bay", "Spanish Town"],
      HT: ["Puerto Príncipe", "Cabo Haitiano"],
      TT: ["Puerto España", "San Fernando"],
      BS: ["Nassau", "Freeport"],
      BB: ["Bridgetown"],
      CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga", "Pereira", "Santa Marta", "Manizales", "Ibagué", "Cúcuta"],
      VE: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
      EC: ["Quito", "Guayaquil", "Cuenca", "Ambato"],
      PE: ["Lima", "Arequipa", "Trujillo", "Cusco", "Chiclayo", "Piura"],
      BO: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre"],
      CL: ["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Viña del Mar", "La Serena"],
      AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Mar del Plata", "Salta", "San Miguel de Tucumán"],
      UY: ["Montevideo", "Punta del Este", "Salto"],
      PY: ["Asunción", "Ciudad del Este", "Encarnación"],
      BR: ["São Paulo", "Río de Janeiro", "Brasília", "Salvador", "Belo Horizonte", "Fortaleza", "Curitiba", "Manaus", "Recife", "Porto Alegre"],
      GY: ["Georgetown"],
      SR: ["Paramaribo"],
      ES: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Bilbao", "Las Palmas de Gran Canaria", "Palma de Mallorca", "Alicante"],
      PT: ["Lisboa", "Oporto", "Braga", "Faro"],
      FR: ["París", "Marsella", "Lyon", "Toulouse", "Niza"],
      DE: ["Berlín", "Múnich", "Hamburgo", "Fráncfort", "Colonia"],
      IT: ["Roma", "Milán", "Nápoles", "Turín", "Florencia"],
      GB: ["Londres", "Mánchester", "Birmingham", "Glasgow", "Edimburgo"],
      IE: ["Dublín", "Cork"],
      NL: ["Ámsterdam", "Róterdam", "La Haya"],
      BE: ["Bruselas", "Amberes", "Gante"],
      CH: ["Berna", "Zúrich", "Ginebra", "Basilea"],
      AT: ["Viena", "Salzburgo", "Graz"],
      SE: ["Estocolmo", "Gotemburgo", "Malmö"],
      NO: ["Oslo", "Bergen"],
      DK: ["Copenhague", "Aarhus"],
      FI: ["Helsinki", "Tampere"],
      IS: ["Reikiavik"],
      PL: ["Varsovia", "Cracovia", "Wroclaw"],
      CZ: ["Praga", "Brno"],
      SK: ["Bratislava"],
      HU: ["Budapest"],
      RO: ["Bucarest", "Cluj-Napoca"],
      BG: ["Sofía", "Plovdiv"],
      GR: ["Atenas", "Tesalónica"],
      UA: ["Kiev", "Odesa", "Leópolis"],
      RU: ["Moscú", "San Petersburgo", "Novosibirsk"],
      RS: ["Belgrado", "Novi Sad"],
      HR: ["Zagreb", "Split"],
      SI: ["Liubliana"],
      BA: ["Sarajevo"],
      ME: ["Podgorica"],
      MK: ["Skopie"],
      AL: ["Tirana"],
      LT: ["Vilna", "Kaunas"],
      LV: ["Riga"],
      EE: ["Tallin"],
      MD: ["Chisináu"],
      BY: ["Minsk"],
      LU: ["Luxemburgo"],
      MT: ["La Valeta"],
      CY: ["Nicosia"],
      AD: ["Andorra la Vieja"],
      MC: ["Mónaco"],
      LI: ["Vaduz"],
      SM: ["San Marino"],
      VA: ["Ciudad del Vaticano"],
      TR: ["Istanbul", "Ankara", "Esmirna", "Antalya"],
      CN: ["Pekín", "Shanghái", "Cantón", "Shenzhen", "Hong Kong"],
      JP: ["Tokio", "Osaka", "Yokohama", "Nagoya"],
      KR: ["Seúl", "Busan", "Incheon"],
      KP: ["Pionyang"],
      TW: ["Taipéi", "Kaohsiung"],
      HK: ["Hong Kong"],
      IN: ["Nueva Delhi", "Bombay", "Bangalore", "Calcuta", "Chennai", "Hyderabad"],
      PK: ["Islamabad", "Karachi", "Lahore"],
      BD: ["Daca", "Chittagong"],
      NP: ["Katmandú"],
      LK: ["Colombo", "Kandy"],
      ID: ["Yakarta", "Surabaya", "Bandung", "Bali"],
      PH: ["Manila", "Quezon City", "Cebú", "Davao"],
      VN: ["Hanói", "Ho Chi Minh"],
      TH: ["Bangkok", "Chiang Mai", "Phuket"],
      MY: ["Kuala Lumpur", "Penang", "Johor Bahru"],
      SG: ["Singapur"],
      MM: ["Naipyidó", "Rangún"],
      KH: ["Nom Pen"],
      LA: ["Vientián"],
      MN: ["Ulán Bator"],
      KZ: ["Astaná", "Almaty"],
      UZ: ["Taskent"],
      GE: ["Tiflis"],
      AM: ["Ereván"],
      AZ: ["Bakú"],
      AF: ["Kabul"],
      IR: ["Teherán", "Isfahán"],
      IQ: ["Bagdad", "Basora"],
      SA: ["Riad", "Jeddah", "Meca"],
      AE: ["Dubái", "Abu Dabi", "Sharjah"],
      QA: ["Doha"],
      KW: ["Ciudad de Kuwait"],
      BH: ["Manama"],
      OM: ["Mascate"],
      JO: ["Amán"],
      LB: ["Beirut"],
      SY: ["Damasco", "Alepo"],
      IL: ["Jerusalén", "Tel Aviv", "Haifa"],
      PS: ["Ramala", "Gaza"],
      YE: ["Saná"],
      EG: ["El Cairo", "Alejandría", "Giza"],
      ZA: ["Johannesburgo", "Ciudad del Cabo", "Pretoria", "Durban"],
      NG: ["Abuya", "Lagos", "Kano"],
      KE: ["Nairobi", "Mombasa"],
      ET: ["Adís Abeba"],
      GH: ["Acra", "Kumasi"],
      MA: ["Rabat", "Casablanca", "Marrakech", "Tánger"],
      DZ: ["Argel", "Orán"],
      TN: ["Túnez"],
      LY: ["Trípoli", "Bengasi"],
      SD: ["Jartum"],
      UG: ["Kampala"],
      TZ: ["Dodoma", "Dar es Salam"],
      CM: ["Yaundé", "Duala"],
      CI: ["Abiyán", "Yamusukro"],
      SN: ["Dakar"],
      ML: ["Bamako"],
      NE: ["Niamey"],
      BF: ["Uagadugú"],
      RW: ["Kigali"],
      ZM: ["Lusaka"],
      ZW: ["Harare", "Bulawayo"],
      MZ: ["Maputo"],
      AO: ["Luanda"],
      CD: ["Kinsasa"],
      CG: ["Brazzaville"],
      GA: ["Libreville"],
      NA: ["Windhoek"],
      BW: ["Gaborone"],
      MW: ["Lilongüe"],
      SO: ["Mogadiscio"],
      LR: ["Monrovia"],
      SL: ["Freetown"],
      GM: ["Banjul"],
      GN: ["Conakry"],
      TG: ["Lomé"],
      BJ: ["Porto Novo", "Cotonú"],
      MG: ["Antananarivo"],
      MU: ["Port Louis"],
      AU: ["Canberra", "Sídney", "Melbourne", "Brisbane", "Perth", "Adelaida"],
      NZ: ["Wellington", "Auckland", "Christchurch"],
      FJ: ["Suva"],
      PG: ["Port Moresby"]
    }
  };
})();
